' <auto-generated/>
Imports System.Reflection

<assembly: AssemblyTitleAttribute("WindowsDesktop_VB.NET_WinForms_Example")>
<assembly: AssemblyProductAttribute("QuickGraph")>
<assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms for .NET.")>
<assembly: AssemblyVersionAttribute("0.0.1")>
<assembly: AssemblyFileVersionAttribute("0.0.1")>
Friend NotInheritable Class AssemblyVersionInformation
    Friend Const Version As String = "0.0.1"
End Class
